name: Auto Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
      env:
        CI: true
    - name: Deoploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TOKEN  }}
        ARGS: "-avzr --delete"
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.HOST  }}
        REMOTE_USER: ${{ secrets.USER  }}
        TARGET: "/usr/local/nginx/html/minishop"